USE [Psychology Center]
GO

DROP TABLE ObtainedSpecialization
DROP TABLE THERAPYSESSION
DROP TABLE HoldsW
DROP TABLE PSYCHOLOGIST
DROP TABLE COURSE
DROP TABLE SPECIALIZATION
DROP TABLE HASCondition
DROP TABLE CONDITION
DROP TABLE CLIENT
DROP TABLE Workshop
GO
CREATE TABLE PSYCHOLOGIST(PsychologistID INT PRIMARY KEY,FName VARCHAR(30),LName VARCHAR(30),DOB DATE)
CREATE TABLE CLIENT(ClientID INT PRIMARY KEY,FName VARCHAR(30),LName VARCHAR(30),DOB DATE)
CREATE TABLE SPECIALIZATION(SPECid INT PRIMARY KEY,SName VARCHAR(50),SDesc VARCHAR(100))
CREATE TABLE THERAPYSESSION(TSid INT PRIMARY KEY,TDate DATE,Ttime TIME,Price INT,Pid INT REFERENCES PSYCHOLOGIST(PsychologistID),Cid INT REFERENCES CLIENT(ClientID))
CREATE TABLE COURSE(CSid INT PRIMARY KEY,CNmae VARCHAR(50),Price INT,Sid INT REFERENCES SPECIALIZATION(SPECid))
CREATE TABLE CONDITION(ConID INT PRIMARY KEY,CDescription VARCHAR(200))
CREATE TABLE ObtainedSpecialization(Pid INT REFERENCES PSYCHOLOGIST(PsychologistID),SPECid INT REFERENCES SPECIALIZATION(SPECid),PRIMARY KEY(Pid,SPECid))
CREATE TABLE HASCondition(CID INT REFERENCES CLIENT(ClientID),ConID INT REFERENCES CONDITION(ConID),PRIMARY KEY(CID,ConID))
CREATE TABLE Workshop(Wid INT PRIMARY KEY,WDescription VARCHAR(200),WName VARCHAR(50),Price INT,Duration INT)
CREATE TABLE HoldsW(Pid INT REFERENCES PSYCHOLOGIST(PsychologistID),Wid INT REFERENCES Workshop(Wid),PRIMARY KEY(Pid,Wid))




