(DEFUN MYAPPEND (L1 L2)
	(COND
		((NULL L1) L2)
		(T (CONS (CAR L1)) (MYAPPEND (CDR L1) L2)))
	)
)

(DEFUN MYMEMBER (ELEM LIST)
	(COND
		((ATOM LIST) NIL)
		((EQUAL ELEM (CAR LIST)) LIST)
		(T (MYMEMBER ELEM (CDR LIST)))
	)
)
